cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'

urlpatterns = [
    path('cart/', views.view_cart, name='view_cart'),
    path('add/<int:prise_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('add_prises', views.add_prises, name='add_prises'),
]

fow_admin/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gameplay.urls')),
    path('', include('cart.urls')),
    path('', include('db_admin.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

from gameplay.models import Prises, Users

# Create your models here.
class CartItem(models.Model):
    prise = models.ForeignKey(Prises, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    user = models.ForeignKey(Users, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.quantity} x {self.product.name}'

cart/views.py
from django.http import HttpRequest

# Create your views here.
from django.shortcuts import render, redirect
from .models import CartItem
from gameplay.models import Prises, Users, UsersPrises


def is_authentificated(request:HttpRequest):
    data = request.session.get('user')
    if data:
        user = Users.get_hashed_user(data['user_name'], data['password'])
        if user is not None:
            return user
        else:
            return None
    else:
        return None


def view_cart(request: HttpRequest):
    user = is_authentificated(request)
    cart_items = CartItem.objects.filter(user=is_authentificated(request))
    total_price = sum(item.prise.price_in_scores * item.quantity for item in cart_items)
    scores_to_spend = Users.get_user_stat(user)
    context = {'cart_items': cart_items,
               'total_price': total_price,
               'scores': scores_to_spend,
               }
    return render(request, 'cart/cart.html', context)

def add_to_cart(request, prise_id):
    prise = Prises.objects.get(prise_id=prise_id)
    cart_item, created = CartItem.objects.get_or_create(prise=prise, user=is_authentificated(request))
    cart_item.quantity += 1
    cart_item.save()
    return redirect('exchange')

def remove_from_cart(request: HttpRequest, item_id):
    cart_item = CartItem.objects.get(id=item_id)
    cart_item.delete()
    return redirect('cart:view_cart')


def add_prises(request: HttpRequest):
    cart_items: list[CartItem] = CartItem.objects.all()
    user = is_authentificated(request)
    to_add = []
    for item in cart_items:
        for _ in range(item.quantity):
            to_add.append((item.user, item.prise))
        users_prises = [UsersPrises(user=u, prise=p) for u, p in to_add]
        res = UsersPrises.objects.bulk_create(users_prises)
        if res:
            CartItem.objects.all().delete()
    return redirect('exchange')

templates/cart/cart.html
<!-- cart/cart.html -->

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        /* Add CSS styles for flex container and items */
        .product-list {
            display: flex;
            flex-wrap: wrap; /* Allow items to wrap to the next row if necessary */
            justify-content: space-between; /* Space items evenly along the main axis */
            list-style: none; /* Remove list styles */
            padding: 0;
        }

        .product-item {

            flex: 1; /* Grow to fill available space evenly */
             /* Limit item width to avoid overcrowding */
            margin: 10px; /* Add spacing between items */
            border: 1px solid #ccc; /* Add a border for visual separation */
            padding: 10px;
            text-align: center;
        }

        /* Style the "Buy Now" button */
        .buy-now-button {
            display: block;
            margin-top: 10px;
            background-color: #007bff;
            color: #fff;
            text-decoration: none;
            padding: 5px 10px;
            border-radius: 5px;
        }
    </style>
</head>

<body>

    <h1>Ваша корзина</h1>

    <div class="product-list">



    {% for item in cart_items %}
    <div class="product-item">
        <p>{{ item.prise.prise_description }} ({{ item.quantity }})</p>
        <p>Стоимость: {{ item.prise.price_in_scores }} очков </p>
        <a href="{% url 'cart:remove_from_cart' item.id %}">Убрать</a>
    </div>
    {% empty %}
    <p>Корзина пуста.</p>
    {% endfor %}

    </div>

    <p>К оплате: {{ total_price }}</p>
    <p>Доступно: {{ scores }}</p>

    <a href="{% url 'exchange' %}">Продолжить выбор купонов</a><br>
    {% if total_price <= scores %}
    <a href="{% url 'cart:add_prises' %}">Оформить покупку</a>
    {% else %}
    <p>Недостаточно очков для покупки! </p>
    {% endif %}

</body>

</html>