cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'

urlpatterns = [
    path('cart/', views.view_cart, name='view_cart'),
    path('add/<int:prise_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('add_prises', views.add_prises, name='add_prises'),
]

db_admin/urls.py
from django.urls import path
from db_admin import views
from gameplay.models import Words

app_name = 'db_admin'


urlpatterns = [
    path('admin_home/', views.admin_home, name='admin_home'),

    path('word', views.WordsListView.as_view(), name='word_list'),
    path('word/new/', views.WordCreateView.as_view(), name='word_create'),
    path('word/<int:pk>/edit/', views.WordUpdateView.as_view(), name='word_update'),
    path('word/<int:pk>/delete/', views.WordDeleteView.as_view(), name='word_delete'),

    path('score', views.ScoresListView.as_view(), name='score_list'),
    path('score/new/', views.ScoreCreateView.as_view(), name='score_create'),
    path('score/<int:pk>/edit/', views.ScoreUpdateView.as_view(), name='score_update'),
    path('score/<int:pk>/delete/', views.ScoreDeleteView.as_view(), name='score_delete'),

    path('prise', views.PrisesListView.as_view(), name='prise_list'),
    path('prise/new/', views.PriseCreateView.as_view(), name='prise_create'),
    path('prise/<int:pk>/edit/', views.PriseUpdateView.as_view(), name='prise_update'),

    path('categorie', views.CategorieListView.as_view(), name='categorie_list'),
    path('categorie/new/', views.CategorieCreateView.as_view(), name='categorie_create'),
    path('categorie/<int:pk>/edit/', views.CategorieUpdateView.as_view(), name='categorie_update'),

    path('card', views.CardListView.as_view(), name='card_list'),

    path('user', views.UserListView.as_view(), name='user_list'),
    path('user/new/', views.UserCreateView.as_view(), name='user_create'),
    path('user/<int:pk>/edit/', views.UserUpdateView.as_view(), name='user_update'),

]

fow_admin/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gameplay.urls')),
    path('', include('cart.urls')),
    path('', include('db_admin.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

db_admin/models.py
from django.db import models

# Create your models here.

db_admin/forms.py
import re
from db_admin.models import Users
from django import forms
from django.core.validators import RegexValidator
from django.core.exceptions  import ValidationError


class SignUpForm(forms.Form):
    card_no = forms.IntegerField(max_value=1000000, min_value=100001, label="Номер карты", help_text="Карта лояльности")
    user_name = forms.CharField(max_length=254, min_length=3, label="Имя пользователя")
    password = forms.CharField(max_length=254, min_length=6, label="Пароль")
    confirm_password = forms.CharField(max_length=254, min_length=6, label="Пароль подтв.")


    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_pass = cleaned_data.get("confirm_password")

        if password != confirm_pass:
            raise forms.ValidationError("Пароли не совпадают.")


class LoginForm(forms.Form):
    username = forms.CharField(label='Имя пользователя')
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)


class GameForm(forms.Form):

    def ru_ru_validator(word):
        print('are we here')
        regex = r'[а-яА-ЯЁё]'
        res = all(map(lambda x: re.findall(regex, x), word))
        print(f'res = {res}')
        if res:
            return word
        else:
            print('Error? Error!')
            raise ValidationError('Только буквы кириллицы, пробел и дефис')

    word = forms.CharField(
        validators=[ru_ru_validator],
        min_length=1,
        required=True,
        label="Введи букву или слово",
        )


    def __str__(self):
        return self.word

db_admin/views.py
from django.http import HttpRequest
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from gameplay.models import Words, Users, Scores, Prises, Rounds, Games, Cards, Categories

#all views


def admin_home(request: HttpRequest):
    return render(request, 'db_admin/admin_home.html')


#WORDS
class WordsListView(ListView):
    model = Words
    template_name = 'db_admin/word_list.html'


class WordDetailView(DetailView):
    model = Words
    template_name = 'db_admin/word_detail.html'


class WordCreateView(CreateView):

    model = Words
    template_name = 'db_admin/word_update.html'
    fields = ['word', 'description']

    success_url = reverse_lazy('db_admin:word_list')


class WordUpdateView(UpdateView):

    model = Words
    template_name = 'db_admin/word_update.html'
    fields = ['word', 'description']

    success_url = reverse_lazy('db_admin:word_list')


class WordDeleteView(DeleteView):

    model = Words
    template_name = 'db_admin/word_confirm_delete.html'

    success_url = reverse_lazy('db_admin:word_list')


#SCORES
class ScoresListView(ListView):
    model = Scores
    template_name = 'db_admin/score_list.html'


class ScoreCreateView(CreateView):

    model = Scores
    template_name = 'db_admin/score_update.html'
    fields = ['score']

    success_url = reverse_lazy('db_admin:score_list')


class ScoreUpdateView(UpdateView):

    model = Scores
    template_name = 'db_admin/score_update.html'
    fields = ['score']

    success_url = reverse_lazy('db_admin:score_list')


class ScoreDeleteView(DeleteView):

    model = Scores
    template_name = 'db_admin/score_delete.html'

    success_url = reverse_lazy('db_admin:score_list')


#PRISES
class PrisesListView(ListView):
    model = Prises
    template_name = 'db_admin/prise_list.html'


class PriseCreateView(CreateView):

    model = Prises
    template_name = 'db_admin/prise_update.html'
    fields = ['prise_description', 'discount_value', 'price_in_scores', 'categorie', 'to_show']

    success_url = reverse_lazy('db_admin:prise_list')


class PriseUpdateView(UpdateView):

    model = Prises
    template_name = 'db_admin/prise_update.html'
    fields = ['prise_description', 'discount_value', 'price_in_scores', 'categorie', 'to_show']

    success_url = reverse_lazy('db_admin:prise_list')


#CATEGORIES
class CategorieListView(ListView):
    model = Categories
    template_name = 'db_admin/categorie_list.html'


class CategorieCreateView(CreateView):

    model = Categories
    template_name = 'db_admin/categorie_update.html'
    fields = ['categorie_name', 'categorie_img']

    success_url = reverse_lazy('db_admin:categorie_list')


class CategorieUpdateView(UpdateView):

    model = Categories
    template_name = 'db_admin/categorie_update.html'
    fields = ['categorie_name', 'categorie_img']

    success_url = reverse_lazy('db_admin:categorie_list')


#CARDS
class CardListView(ListView):
    model = Cards
    template_name = 'db_admin/cards_list.html'


#USERS
class UserListView(ListView):
    model = Users
    template_name = 'db_admin/user_list.html'


class UserCreateView(CreateView):

    model = Users
    template_name = 'db_admin/user_update.html'
    fields = ['user_name', 'password', 'is_admin']

    success_url = reverse_lazy('db_admin:user_list')


class UserUpdateView(UpdateView):

    model = Users
    template_name = 'db_admin/user_update.html'
    fields = ['is_admin']

    def get_context_data(self, **kwargs):
        context = super(UserUpdateView, self).get_context_data(**kwargs)
        context['login'] = self.get_object().user_name
        return context

    success_url = reverse_lazy('db_admin:user_list')

templates/db_admin/cards_update.html
{% extends 'db_admin/admin_layout.html' %}


{% block content %}

{% if object %}
    <h1>Изменить очки</h1>
{% else %}
    <h1>Добавить очки</h1>
{% endif %}

<form method="post">
    {% csrf_token %}
    <ul class="prises-list">
        <li class="prises-item">
            {{ form.as_p }}
            <input class="submit-button" type="submit" value="Подтвердить"/>
        </li>
    </ul>
</form>


{% endblock %}

templates/db_admin/categorie_update.html
{% extends 'db_admin/admin_layout.html' %}


{% block content %}

{% if object %}
    <h1>Изменить категорию</h1>
{% else %}
    <h1>Добавить категорию</h1>
{% endif %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <ul class="prises-list">
        <li class="prises-item">
            {{ form.as_p }}
            <input class="submit-button" type="submit" value="Подтвердить"/>
        </li>
    </ul>
</form>


{% endblock %}

templates/db_admin/exchange.html
{% extends "db_admin/layout.html" %}

{% block content %}
    <div class="stats">
    <h1>Магазин купонов</h>
        <br>
    <h2>Игрок: {{ user }}</h2>
    <h2>Доступные очки: {{ scores }}</h2>
    </div>

    <ul class="prises-list">
        {% for prise in prises %}
            <li class="prises-item">
                <img src="static/db_admin/img/{{ prise.categorie.categorie_id }}.jpg" alt="{{ prise.categorie.categorie_name }}">
                <h2>{{prise.categorie.categorie_name}}</h2>
                <p>{{prise.prise_description}}</p>
                <p>Размер скидки {{prise.discount_value}}</p>
                <p>Стоимость в баллах {{prise.price_in_scores}}</p>
                <a href="#" class="buy-now-button">Buy Now</a><br>
                <a class="buy-now-button" href="{% url 'cart:add_to_cart' prise.prise_id %}">Add to Cart</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/db_admin/game.html
{% extends "db_admin\layout.html" %}

{% block content %}
<div class="game">
  <h2>Привет, {{ user.user_name }}!</h2>
  <h2>Задание</h2>
  <h2>{{ word.description }}</h2>
  <h1>{{ word_to_show }}</h1>
  <h2>Названные буквы</h2>
  <h2>{{ letters }}</h2>
  {% if score %}
  <form action="{% url 'game' %}" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <button type="submit" class="btn btn-primary">Угадать</button>
  </form>
  {% endif %}
  <h2>БАРАБАН</h2>
  {% if score %}
    <h2>На барабане выпало:</h2>
    <h2>{{ score }} очков </h2>
  {% elif prise %}
    <h2>На барабане выпало:</h2>
    <h2>{{ prise.prise_description }} </h2>
    <a href="{% url 'take_prise' %}" class="btn btn-primary">
      Взять приз
    </a>
  {% endif %}
  {% if not score %}
  <a href="{% url 'rotate' %}" class="btn btn-primary">
    Вращать барабан
  </a>
  {% endif %}
</div>
{% endblock %}

templates/db_admin/game_base.html
{% extends "db_admin\layout.html" %}

{% block content %}
<div class="game">
    <h2>Привет, {{ user.user_name }}!</h2>
    <br>
    <h2>Задание: {{ word.description }}</h2>
    <h1>Слово:   {{ word_to_show }}</h1>
    <h2>Названные буквы:
        {% if letters %}
            {{ letters }}
        {% endif %}
    </h2><br>
    {% block game_content %}
    {% endblock %}
</div>
{% endblock %}

templates/db_admin/game_guess.html
{% extends "db_admin\game_base.html" %}

{% block game_content %}
    <form action="{% url 'game_guess' %}" method="post">
        {% csrf_token %}
        {{ form.as_table }}
        <!--
        <span class="input-group-text">@ник в Телеграме</span>
        {{ form.word }}
        </div>
        -->
        <button type="submit" class="btn btn-primary">Угадать</button>
    </form>
    {% if err %}
    <div class="error">
        <h4>{{ err }}</h4>
    </div>
    {%  endif %}
    <br>
    <h2>БАРАБАН</h2>
    <h4>На барабане выпало: {{ score }} очков </h4>
{% endblock %}

templates/db_admin/game_prise.html
{% extends "db_admin\game_base.html" %}

{% block game_content %}
    <h2>На барабане выпало: {{ prise.prise_description }}</h2>
    <a href="{% url 'take_prise' %}" class="btn btn-primary">
    Взять приз
    </a>
    <a href="{% url 'rotate' %}" class="btn btn-primary">
    Вращать барабан
    </a>
{% endblock %}

templates/db_admin/game_score.html
{% extends "db_admin\game_base.html" %}


{% block game_content %}
<a href="{% url 'rotate' %}" class="btn btn-primary">
    Вращать барабан
</a>
{% endblock %}

templates/db_admin/prise_update.html
{% extends 'db_admin/admin_layout.html' %}


{% block content %}

{% if object %}
    <h1>Изменение приза</h1>
{% else %}
    <h1>Добавление приза</h1>
{% endif %}

<form method="post">
    {% csrf_token %}
    <ul class="prises-list">
        <li class="prises-item">
            {{ form.as_p }}
            <input class="submit-button" type="submit" value="Подтвердить"/>
        </li>
    </ul>
</form>


{% endblock %}

templates/db_admin/score_delete.html
{% extends 'db_admin/admin_layout.html' %}


{% block content %}

<h1>Удалить очки</h1>
    <form method="post">
        {% csrf_token %}
        <ul class="prises-list">
            <li class="prises-item">
                <p>Вы уверены что хотите удалить позицию?</p>
                <input class="submit-button" type="submit" value="Подтвердить"/>
            </li>
        </ul>

    </form>

{% endblock %}

templates/db_admin/statistics.html
{% extends "db_admin/layout.html" %}

{% block content %}
    <h1 class="stats">Статистика</h>
    <table class="stats">
        <thead>
            <tr>
                <th>Игрок</th>
                <!--Настроить переходы ASC / DESC-->
                <th><a href="">Очки</a></th>
                <th><a href="">Победы</a></th>
            </tr>
        </thead>
        <tbody>
            {% for st in stats %}
                <tr>
                    {% for cell in st %}
                        <td>{{ cell }}</td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/db_admin/word_detail.html
{% extends 'db_admin/admin_layout.html' %}


{% block content %}

<h1>Слово</h1>

<ul class="prises-list">
    <li class="prises-item">
        <p>ID: {{ object.word_id }}</p>
        <p>Слово: {{ object.word }}</p>
        <p>Описание: {{ object.description }}</p>
        <p>Сложность: {{ object.difficulty }}</p>
        <p><a class="buy-now-button" href="{% url 'db_admin:word_update' object.word_id %}">Изменить</a></p>
    </li>
</ul>


{% endblock %}

templates/db_admin/word_list.html
{% extends 'db_admin/admin_layout.html' %}


{% block content %}

<h1>Слова</h1>

<ul class="prises-list">
	{% for word in object_list %}
    <li class="prises-item">
        <p>{{ word.word }}</p>
        <p>{{ word.description }}</p>
        <p>Сложность: {{ word.difficulty }}</p>

        <p><a class="buy-now-button" href="{% url 'db_admin:word_update' word.word_id %}">Изменить</a></p>

    </li>
	{% endfor %}
    <li class="prises-item">
    <a href="{% url 'db_admin:word_create' %}">Добавить слово</a>
    </li>
</ul>


{% endblock %}

templates/db_admin/word_update.html
{% extends 'db_admin/admin_layout.html' %}


{% block content %}

{% if object %}
    <h1>Изменить слово</h1>
{% else %}
    <h1>Добавить слово</h1>
{% endif %}

<form method="post">
    {% csrf_token %}
    <ul class="prises-list">
        <li class="prises-item">
            {{ form.as_p }}
            <input class="submit-button" type="submit" value="Подтвердить"/>
        </li>
    </ul>
</form>


{% endblock %}