cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'

urlpatterns = [
    path('cart/', views.view_cart, name='view_cart'),
    path('add/<int:prise_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('add_prises', views.add_prises, name='add_prises'),
]

fow_admin/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gameplay.urls')),
    path('', include('cart.urls')),
    path('', include('db_admin.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gameplay/urls.py
from django.urls import path
from gameplay import views

urlpatterns = [
    path("", views.home_view, name="home"),
    path("signup", views.signup_view, name="registration"),
    path("login", views.login_view, name="login"),
    path("rules", views.rules_view, name="rules"),
    path("statistics", views.statistics_view, name="statistics"),
    path("exchange", views.exchange_view, name="exchange"),
    path("new_game", views.new_game, name="new_game"),
    path("game_score", views.game_score_view, name="game_score"),
    path("game_prise", views.game_prise_view, name="game_prise"),
    path("game_guess", views.game_guess_view, name="game_guess"),
    path("rotate", views.rotate_drum, name="rotate"),
    path("take_prise", views.take_prise, name="take_prise"),
    path("finish", views.finish_view, name="finish"),
    path("logout", views.logout_view, name="logout"),
    path("coupons", views.coupons_view, name="coupons"),
]

gameplay/forms.py
import re
from gameplay.models import Users
from django import forms
from django.core.validators import RegexValidator
from django.core.exceptions  import ValidationError


class SignUpForm(forms.Form):
    card_no = forms.IntegerField(max_value=1000000, min_value=100001, label="Номер карты", help_text="Карта лояльности")
    user_name = forms.CharField(max_length=254, min_length=3, label="Имя пользователя")
    password = forms.CharField(max_length=254, min_length=6, label="Пароль")
    confirm_password = forms.CharField(max_length=254, min_length=6, label="Пароль подтв.")


    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_pass = cleaned_data.get("confirm_password")

        if password != confirm_pass:
            raise forms.ValidationError("Пароли не совпадают.")


class LoginForm(forms.Form):
    username = forms.CharField(label='Имя пользователя')
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)


class GameForm(forms.Form):

    def ru_ru_validator(word):
        print('are we here')
        regex = r'[а-яА-ЯЁё]'
        res = all(map(lambda x: re.findall(regex, x), word))
        print(f'res = {res}')
        if res:
            return word
        else:
            print('Error? Error!')
            raise ValidationError('Только буквы кириллицы, пробел и дефис')

    word = forms.CharField(
        validators=[ru_ru_validator],
        min_length=1,
        required=True,
        label="Введи букву или слово",
        )


    def __str__(self):
        return self.word

gameplay/views.py
import hashlib
from django.forms import ValidationError
from django.http import HttpRequest, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from .forms import GameForm, SignUpForm, LoginForm
from gameplay.models import Users, Cards, Words, Games, Rounds, Prises, Scores, UsersPrises
from django.forms.models import model_to_dict
import random as rnd


#Набор игровых данных
# class GameStats:
#     def __init__(self, user: Users):
#         self.word: Words = None
#         self.word_show = None
#         self.game: Games = Games.add_game(self.word, user)
#         self.ground: Rounds = None
#         self.letters: set = set()
#         self.status: str = None


#         if self.word is None:
#             self.word = Words.get_word()


#         if self.word_show is None:
#             self.word_show = ''.join(['*']*len(self.word.word))


#Проверка сесии
def is_authentificated(request:HttpRequest):
    data = request.session.get('user')
    if data:
        user = Users.get_hashed_user(data['user_name'], data['password'])
        if user is not None:
            return user
        else:
            return None
    else:
        return None


#Домашняя страница
def home_view(request: HttpRequest):
    user = is_authentificated(request)
    context = {
        'user': user
    }
    return render(request, 'gameplay/home.html', context)


#Регистрация пользователя и карты
def signup_view(request: HttpRequest):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            card_no = form.cleaned_data.get("card_no")
            name = form.cleaned_data.get("user_name")
            password = form.cleaned_data.get("password")
            if Cards.is_card_spare(card_no):
                user = Users.get_user(name, password)
                if user is None:
                    user = Users.add_user(name, password)
                    data = model_to_dict(user)
                    request.session['user'] =  data
                card = Cards.get_card(card_no)
                card.user_id = user.user_id
                card.save()             # Сохраняем пару пользователь-карта
            return redirect('home')     # Перенаправляем на главную страницу
    else:
        form = SignUpForm()
    return render(request, 'gameplay/signup.html', {'form': form, 'user': None})


#Логин
def login_view(request: HttpRequest):
    form = LoginForm(data=request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = Users.get_user(username, password)
            if user is not None:
                data = model_to_dict(user)
                request.session['user'] =  data   # Выполняем вход
                return redirect('home')  # Перенаправляем на главную страницу
    return render(request, 'gameplay/login.html', {'form': form, 'user': None})



#Создание новой игры
def new_game(request: HttpRequest):
    user = is_authentificated(request)
    if user is None:
        return redirect('home')
    else:
        word = Words.get_word()
        game: Games = Games.add_game(word, user)
        request.session['game_id'] = str(game.game_id)
        request.session['drum_score'] = None
        request.session['drum_prise'] = None
        request.session['err'] = None
        return redirect("game_score")


#Вращиениебарабана
def rotate_drum(request: HttpRequest):
    prises = Prises.objects.filter(price_in_scores=0)
    scores = Scores.objects.all()
    drum = []
    drum.extend(scores)
    [drum.append(rnd.choice(prises)) for _ in range(5)]
    drum_sector = rnd.choice(drum)
    if isinstance(drum_sector, Scores):
        request.session['drum_score'] = drum_sector.score
        request.session['drum_prise'] = None
        return redirect("game_guess")   #Выпали очки, идем гадать букву или слово
    elif isinstance(drum_sector, Prises):
        request.session['drum_score'] = None
        request.session['drum_prise'] = drum_sector.prise_id
        return redirect("game_prise")   #Выпал приз, брать/не брать
    else:
        raise ValueError('Похоже что барабан сломался :(')  # Выпало что-то совсем не то


#Взять приз
def take_prise(request: HttpRequest):
    prise = Prises.objects.get(prise_id=request.session.get('drum_prise'))
    user = is_authentificated(request)
    user_pr = UsersPrises(user_id=user.pk, prise_id=prise.pk)
    user_pr.save()
    request.session['game_id'] = None
    return redirect('finish')


def game_score_view(request: HttpRequest):
    user = is_authentificated(request)
    if user is None:
        return redirect('home')
    elif request.session.get('game_id') is None:
        return redirect('new_game')
    else:
        game = Games.objects.get(game_id=request.session.get('game_id'))
        if game.is_finished():
            return redirect('home')
        if user.user_id != game.user_id:
            raise ValueError('Данные испорчены')
        else:
            _, word_hidden = Words.word_to_show(game)
            prise = request.session.get('drum_prise')
            score = request.session.get('drum_score')
            if prise is not None:
                prise = Prises.objects.get(prise_id=request.session.get('drum_prise'))
            context = {
                'user': user,
                'word': Words.objects.get(word_id=game.word.word_id),
                'word_to_show': word_hidden,
                'letters': game.letters,
                'score': score,
                'prise': prise,
            }
    return render(request, 'gameplay/game_score.html', context)


def game_prise_view(request: HttpRequest):
    user = is_authentificated(request)
    if user is None:
        return redirect('home')
    elif request.session.get('game_id') is None:
        return redirect('new_game')
    else:
        game = Games.objects.get(game_id=request.session.get('game_id'))
        if game.is_finished():
            return redirect('home')
        if user.user_id != game.user_id:
            raise ValueError('Данные испорчены')
        else:
            letters = set(game.letters)
            _, word_hidden = Words.word_to_show(game, letters)
            prise = request.session.get('drum_prise')
            score = None
            if prise is not None:
                prise = Prises.objects.get(prise_id=request.session.get('drum_prise'))
            context = {
                'user': user,
                'word': Words.objects.get(word_id=game.word.word_id),
                'word_to_show': word_hidden,
                'letters': game.letters,
                'score': score,
                'prise': prise,
            }
    return render(request, 'gameplay/game_prise.html', context)


def game_guess_view(request: HttpRequest):
    user = is_authentificated(request)
    if user is None:
        return redirect('home')
    elif request.session.get('game_id') is None:
        return redirect('new_game')
    else:
        game = Games.objects.get(game_id=request.session.get('game_id'))
        if game.is_finished():
            return redirect('home')
        if user.user_id != game.user_id:
            raise ValueError('Данные испорчены')
        else:
            letters = set(game.letters)
            _, word_hidden = Words.word_to_show(game, letters)
            score = request.session.get('drum_score')
            context = {
                'user': user,
                'word': Words.objects.get(word_id=game.word.word_id),
                'word_to_show': word_hidden,
                'letters': game.letters,
                'score': score,
                'prise': None,
            }
            if request.method == 'POST':
                form = GameForm(request.POST)
                if form.is_valid():
                    request.session['err'] = None
                    word = form.cleaned_data['word'].upper()
                    if len(word) == 1:
                        letters.add(word)
                        Games.update_game_letters(game, letters)
                        count, word_hidden = Words.word_to_show(game, letters, word_hidden)
                        context['word_to_show'] = word_hidden
                        scores = count * score
                        is_guessed = False
                        if '*' not in word_hidden:
                            is_guessed = True
                            Rounds.add_round(game, scores, is_guessed)
                            return redirect('finish', context)
                        Rounds.add_round(game, scores, is_guessed)
                    else:
                        if word.upper() == context.get('word').word.upper():
                            scores = score * len(word)
                            res = word.upper()
                            request.session['clear_word'] = res
                            is_guessed = True
                            Rounds.add_round(game, scores, is_guessed)
                            return redirect('finish')
                else:
                    form = GameForm()
                    context['form'] = form
                    context['err'] = '*Только буквы кириллицы'
                    return render(request, 'gameplay/game_guess.html', context)
                request.session['drum_score'] = None
                return redirect('game_score')
            else:
                form = GameForm()
                context['form'] = form
                return render(request, 'gameplay/game_guess.html', context)



def finish_view(request: HttpRequest):
    prise = None
    pr = request.session.get('drum_prise')
    if pr:
        prise = Prises.objects.get(prise_id=pr)
    word = request.session.get('clear_word')
    context = {
        'prise': prise,
        'word': word,
    }

templates/gameplay/base.html
{% extends "gameplay/layout.html" %}


{% block content %}
  <div class="features">
    <h2>Добро пожаловать в игру, {{ player }} </h2>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary">Подтвердить</button>
    </form>
  </div>
{% endblock %}

templates/gameplay/exchange.html
{% extends "gameplay/layout.html" %}

{% block content %}
    <div class="stats">
    <h1>Магазин купонов</h>
        <br>
    <h2>Игрок: {{ user }}</h2>
    <h2>Доступные очки: {{ scores }}</h2>
    </div>

    <ul class="prises-list">
        {% for prise in prises %}
            <li class="prises-item">
                {% if prise.categorie.categorie_img %}
                    <img class="prises_img" src="{{ prise.categorie.categorie_img.url }}">
                {% endif %}
                <h2>{{prise.categorie.categorie_name}}</h2>
                <p>{{prise.prise_description}}</p>
                <p>Размер скидки: {{prise.discount_value}}</p>
                <p>Стоимость в баллах: {{prise.price_in_scores}}</p>
                <a href="#" class="buy-now-button">Приобрести</a><br>
                <a class="buy-now-button" href="{% url 'cart:add_to_cart' prise.prise_id %}">Добавить в корзину</a>
            </li>
        {% endfor %}

        <a class="buy-now-button" href="{% url 'cart:view_cart' %}">Перейти в корзину</a>
    </ul>
{% endblock %}

templates/gameplay/finish.html
{% extends "gameplay/layout.html" %}

{% block content %}
    <div class="features">
        {% if prise %}
        <h1>Поздравляем, Вы выбрали сектор приз:</h1>
        <h1>{{ prise.prise_description }}!</h1>
        {% elif word %}
        <h1>Поздравляем, Вы разгадали слово:</h1>
        <h1>{{ word }}!</h1>
        {% endif %}
        <h1>Игра окончена. Хотите начать новую?</h1>
        <a href="{% url 'new_game' %}" class="btn btn-primary">
            Начать новую игру
        </a>
    </div>
{% endblock %}

templates/gameplay/game.html
{% extends "gameplay/layout.html" %}

{% block content %}
<div class="game">
  <h2>Привет, {{ user.user_name }}!</h2>
  <h2>Задание</h2>
  <h2>{{ word.description }}</h2>
  <h1>{{ word_to_show }}</h1>
  <h2>Названные буквы</h2>
  <h2>{{ letters }}</h2>
  {% if score %}
  <form action="{% url 'game' %}" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <button type="submit" class="btn btn-primary">Угадать</button>
  </form>
  {% endif %}
  <h2>БАРАБАН</h2>
  {% if score %}
    <h2>На барабане выпало:</h2>
    <h2>{{ score }} очков </h2>
  {% elif prise %}
    <h2>На барабане выпало:</h2>
    <h2>{{ prise.prise_description }} </h2>
    <a href="{% url 'take_prise' %}" class="btn btn-primary">
      Взять приз
    </a>
  {% endif %}
  {% if not score %}
  <a href="{% url 'rotate' %}" class="btn btn-primary">
    Вращать барабан
  </a>
  {% endif %}
</div>
{% endblock %}

templates/gameplay/game_base.html
{% extends "gameplay/layout.html" %}

{% block content %}
<div class="game">
    <h2>Привет, {{ user.user_name }}!</h2>
    <br>
    <h2>Задание: {{ word.description }}</h2>
    <h1>Слово:   {{ word_to_show }}</h1>
    <h2>Названные буквы:
        {% if letters %}
            {{ letters }}
        {% endif %}
    </h2><br>
    {% block game_content %}
    {% endblock %}
</div>
{% endblock %}

templates/gameplay/game_guess.html
{% extends "gameplay/game_base.html" %}

{% block game_content %}
    <form action="{% url 'game_guess' %}" method="post">
        {% csrf_token %}
        {{ form.as_table }}
        <!--
        <span class="input-group-text">@ник в Телеграме</span>
        {{ form.word }}
        </div>
        -->
        <button type="submit" class="btn btn-primary">Угадать</button>
    </form>
    {% if err %}
    <div class="error">
        <h4>{{ err }}</h4>
    </div>
    {%  endif %}
    <br>
    <h2>БАРАБАН</h2>
    <h4>На барабане выпало: {{ score }} очков </h4>
{% endblock %}

templates/gameplay/game_prise.html
{% extends "gameplay/game_base.html" %}

{% block game_content %}
    <h2>На барабане выпало: {{ prise.prise_description }}</h2>
    <a href="{% url 'take_prise' %}" class="btn btn-primary">
    Взять приз
    </a>
    <a href="{% url 'rotate' %}" class="btn btn-primary">
    Вращать барабан
    </a>
{% endblock %}

templates/gameplay/game_score.html
{% extends "gameplay/game_base.html" %}


{% block game_content %}
<a href="{% url 'rotate' %}" class="btn btn-primary">
    Вращать барабан
</a>
{% endblock %}

templates/gameplay/home.html
{% extends "gameplay/layout.html" %}

{% block content %}
    <div class="features">
        {% if user %}
            <h1>Добро пожаловать на игру поле чудес, {{ user.user_name }}!</h1>
            <a href="{% url 'new_game' %}" class="btn btn-primary">
                Начать новую игру
            </a>
        {% else %}
            <h1>Добро пожаловать на игру поле чудес!</h1>
            <h2>Для начала работы с приложением необходимо войти или зарегистрироваться.</h2>
            <h2>Для регистрации Вам понадобится номер Вашей карты лояльности.</h2>
            <a href="{% url 'login' %}" class="btn btn-primary">
                Войти
            </a>
        {% endif %}
    </div>
{% endblock %}

templates/gameplay/login.html
{% extends "gameplay/layout.html" %}

{% block content %}
  <div class="login">
    <h2>Авторизация пользователя</h2>
    <form method="post">
      {% csrf_token %}
      <table>
      {{ form.as_table }}
      </table>
      <button type="submit" class="btn btn-primary">Войти</button>
    </form>
  </div>
{% endblock %}

templates/gameplay/my_coupons.html
{% extends "gameplay/layout.html" %}

{% block content %}
    <div class="stats">
    <h2>Игрок: {{ user }}</h2>
    <h2>Доступные очки: {{ scores }}</h2>
    </div>

    <ul class="prises-list">
        {% for prise in prises %}
            <li class="prises-item">
                {% for p in prise %}
                    <p>{{p}}</p>
                {% endfor %}
            </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/gameplay/rules.html
{% extends "gameplay/layout.html" %}


{% block content %}
<div class="rules">
    <h1>    Правила игры</h1>
    <h2>1 Необходимо зарегистрироваться или войти если уже зарегистрированы</h2>
    <h3>    1.1 Новая регистрация только с привзякой по номеру карты лояльности</h3>
    <h2>2 После запуска новой игры будет предложено слово для отгдадывания</h2>
    <h2>3 Перед тем как ввести букву или слово необходимо прокрутить барабан, на котором выпадут очки или сектор приз</h2>
    <h3>3.1 Если игрок не желает забратьпризи закончить игру он должен продолжитьвращатьбарабан</h2>
    <h2>4 Ввести букву или слово целиком</h2>
    <h2>    4.1 Количество попыток влияет на количество очков за игру</h2>
    <h2>5 В любой момент можно посмотреть правила, статистику победителей, магазин купонов, набор своих купонов</h2>
</div>
{% endblock content %}

templates/gameplay/signup.html
{% extends "gameplay/layout.html" %}


{% block content %}
  <div class="login">
    <h2>Регистрация нового пользователя</h2>
    <form method="post">
      {% csrf_token %}
      <table>
      {{ form.as_table }}
      </table>
      <button type="submit" class="btn btn-primary">Подтвердить</button>
    </form>
  </div>
{% endblock %}

templates/gameplay/statistics.html
{% extends "gameplay/layout.html" %}

{% block content %}
    <h1 class="stats">Статистика</h>
    <table class="stats">
        <thead>
            <tr>
                <th>Игрок</th>
                <!--Настроить переходы ASC / DESC-->
                <th><a href="">Очки</a></th>
                <th><a href="">Победы</a></th>
            </tr>
        </thead>
        <tbody>
            {% for st in stats %}
                <tr>
                    {% for cell in st %}
                        <td>{{ cell }}</td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}